/**
 * 产品列表（导航、侧栏、页脚、首页产品区共用）
 * 增删产品：改此文件 + 新建 products/产品id/index.html
 */
window.SITE_PRODUCTS = [
  {
    id: 'cloudris',
    label: 'CloudRIS 云影像信息系统',
    path: 'products/cloudris/index.html',
    summary: '面向放射科/影像科的云 RIS，覆盖登记、报告、审核、签发与统计全流程。',
    image: 'products/cloudris/examlist.webp',
    thumb: 'products/cloudris/examlist.thumb.webp',
    imageAlt: 'CloudRIS 云影像信息系统',
  },
  {
    id: 'cloud-film',
    label: '电子影像-云胶片系统',
    path: 'products/cloud-film/index.html',
    summary: '数字胶片与检查服务云平台，支持扫码查报告/影像与统一后台运维管理。',
    image: 'products/cloud-film/检查详情.webp',
    thumb: 'products/cloud-film/检查详情.thumb.webp',
    imageAlt: '云胶片系统界面示意',
  },
  {
    id: 'dcmviewer-bs',
    label: 'DCMViewer · BS医学影像浏览器',
    path: 'products/dcmviewer-bs/index.html',
    summary: 'Web 专业阅片浏览器，支持 2D/MPR、多端自适配、报告选图与打印。',
    image: 'products/dcmviewer-bs/桌面端.webp',
    thumb: 'products/dcmviewer-bs/桌面端.thumb.webp',
    imageAlt: 'DCMViewer · BS 医学影像浏览器',
  },
  {
    id: 'pacs-storage',
    label: 'PACS医学影像存储系统',
    path: 'products/pacs-storage/index.html',
    summary: '提供 DICOM 全栈服务与存储管理能力的专业影像存储系统。',
    image: 'products/pacs-storage/控制台.webp',
    thumb: 'products/pacs-storage/控制台.thumb.webp',
    imageAlt: 'PACS 医学影像存储系统',
  },
  {
    id: 'unaccompanied-care',
    label: '免陪照护服务管理系统',
    path: 'products/unaccompanied-care/index.html',
    summary: '面向医院免陪照护场景，支持下单、派单、质控与结算的全流程闭环管理。',
    image: 'products/unaccompanied-care/unaccompanied-care.webp',
    thumb: 'products/unaccompanied-care/unaccompanied-care.thumb.webp',
    imageAlt: '免陪照护服务管理系统',
  },
  {
    id: 'medical-records-archive',
    label: '病案无纸化归档系统',
    path: 'products/medical-records-archive/index.html',
    summary: '面向医院病案管理的无纸化归档系统，支持自动归档、加密水印与借阅审批。',
    image: 'products/medical-records-archive/medical-records-archive.webp',
    thumb: 'products/medical-records-archive/medical-records-archive.thumb.webp',
    imageAlt: '病案无纸化归档系统',
  },
  {
    id: 'mdt-rounds-teleconsultation',
    label: 'MDT会诊/移动查房/远程会诊',
    path: 'products/mdt-rounds-teleconsultation/index.html',
    summary: '覆盖 MDT 会诊、移动查房、远程会诊与病历讨论的一体化协作平台。',
    image: 'products/mdt-rounds-teleconsultation/MDT1.webp',
    thumb: 'products/mdt-rounds-teleconsultation/MDT1.thumb.webp',
    imageAlt: 'MDT 会诊与移动查房',
  },
  {
    id: 'or-checklist',
    label: '手术室物品清点系统',
    path: 'products/or-checklist/index.html',
    summary: '围绕手术室清点流程的信息化系统，提升清点规范化与手术安全管理水平。',
    image: 'products/or-checklist/手术清点登陆.webp',
    thumb: 'products/or-checklist/手术清点登陆.thumb.webp',
    imageAlt: '手术室物品清点系统',
  },
];
