/**
 * 产品列表（导航、侧栏、页脚、首页产品区共用）
 * 增删产品：改此文件 + 新建 products/产品id/index.html
 */
window.SITE_PRODUCTS = [
  {
    id: 'cloudris',
    label: 'CloudRIS 云影像信息系统',
    path: 'products/cloudris/index.html',
    summary: '面向放射科/影像科的云 RIS，覆盖登记、报告、审核、签发与统计全流程。',
    image: 'products/cloudris/examlist.webp',
    thumb: 'products/cloudris/examlist.thumb.webp',
    imageAlt: 'CloudRIS 云影像信息系统',
  },
  {
    id: 'cloud-film',
    label: '电子影像-云胶片系统',
    path: 'products/cloud-film/index.html',
    summary: '数字胶片与检查服务云平台，支持扫码查报告/影像与统一后台运维管理。',
    image: 'products/cloud-film/检查详情.webp',
    thumb: 'products/cloud-film/检查详情.thumb.webp',
    imageAlt: '云胶片系统界面示意',
  },
  {
    id: 'dcmviewer-bs',
    label: 'DCMViewer · BS医学影像浏览器',
    path: 'products/dcmviewer-bs/index.html',
    summary: 'Web 专业阅片浏览器，支持 2D/MPR、多端自适配、报告选图与打印。',
    image: 'products/dcmviewer-bs/桌面端.webp',
    thumb: 'products/dcmviewer-bs/桌面端.thumb.webp',
    imageAlt: 'DCMViewer · BS 医学影像浏览器',
  },
  {
    id: 'pacs-storage',
    label: 'PACS医学影像存储系统',
    path: 'products/pacs-storage/index.html',
    summary: '提供 DICOM 全栈服务与存储管理能力的专业影像存储系统。',
    image: 'products/pacs-storage/控制台.webp',
    thumb: 'products/pacs-storage/控制台.thumb.webp',
    imageAlt: 'PACS 医学影像存储系统',
  },
  {
    id: 'dicom-viewer-cs',
    label: 'DICOM Viewer · 桌面影像查看器',
    path: 'products/dicom-viewer-cs/index.html',
    summary: '基于 .NET 的工作站级 DICOM 查看器，支持高性能阅片与可定制扩展。',
    image: 'products/dicom-viewer-cs/viewer.webp',
    thumb: 'products/dicom-viewer-cs/viewer.thumb.webp',
    imageAlt: 'DICOM Viewer · CS 医学影像查看器',
  },
  {
    id: 'ris-acquisition',
    label: 'RIS/PACS/DICOM影像采集系统',
    path: 'products/ris-acquisition/index.html',
    summary: '院内到中心的数据采集同步平台，支持报告增量采集与影像上传归档。',
    image: 'products/ris-acquisition/采集服务器2.webp',
    thumb: 'products/ris-acquisition/采集服务器2.thumb.webp',
    imageAlt: 'RIS/PACS/DICOM 影像采集系统',
  },
  {
    id: 'av-conference',
    label: '音视频会议系统',
    path: 'products/av-conference/index.html',
    summary: '支持私有化部署的音视频会议能力，可快速集成桌面分享与即时通讯。',
    image: 'products/av-conference/meet.webp',
    thumb: 'products/av-conference/meet.thumb.webp',
    imageAlt: '音视频会议系统',
  },
  {
    id: 'mdt-rounds-teleconsultation',
    label: 'MDT会诊/移动查房/远程会诊',
    path: 'products/mdt-rounds-teleconsultation/index.html',
    summary: '覆盖 MDT 会诊、移动查房、远程会诊与病历讨论的一体化协作平台。',
    image: 'products/mdt-rounds-teleconsultation/MDT1.webp',
    thumb: 'products/mdt-rounds-teleconsultation/MDT1.thumb.webp',
    imageAlt: 'MDT 会诊与移动查房',
  },
  {
    id: 'webapi-integration',
    label: 'Web API集成发布平台',
    path: 'products/webapi-integration/index.html',
    summary: '基于数据库集成的轻量 Web API 平台，支持 SQL/Soap/REST 代理与接口发布。',
    image: 'products/webapi-integration/集成平台1.webp',
    thumb: 'products/webapi-integration/集成平台1.thumb.webp',
    imageAlt: 'Web API 集成发布平台',
  },
  {
    id: 'or-checklist',
    label: '手术室物品清点系统',
    path: 'products/or-checklist/index.html',
    summary: '围绕手术室清点流程的信息化系统，提升清点规范化与手术安全管理水平。',
    image: 'products/or-checklist/手术清点登陆.webp',
    thumb: 'products/or-checklist/手术清点登陆.thumb.webp',
    imageAlt: '手术室物品清点系统',
  },
  {
    id: 'medical-records-archive',
    label: '病案无纸化归档系统',
    path: 'products/medical-records-archive/index.html',
    summary: '面向医院病案管理的无纸化归档系统，支持自动归档、加密水印与借阅审批。',
    image: 'products/medical-records-archive/medical-records-archive.webp',
    thumb: 'products/medical-records-archive/medical-records-archive.thumb.webp',
    imageAlt: '病案无纸化归档系统',
  },
  {
    id: 'unaccompanied-care',
    label: '免陪照护服务管理系统',
    path: 'products/unaccompanied-care/index.html',
    summary: '面向医院免陪照护场景，支持下单、派单、质控与结算的全流程闭环管理。',
    image: 'products/unaccompanied-care/unaccompanied-care.webp',
    thumb: 'products/unaccompanied-care/unaccompanied-care.thumb.webp',
    imageAlt: '免陪照护服务管理系统',
  },
];
